# Generated by Django 4.2.5 on 2023-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=10)),
                ('codigo', models.IntegerField()),
                ('email_institucional', models.EmailField(max_length=254)),
                ('email_personal', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
