# Generated by Django 4.2.5 on 2023-09-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0002_estudiante_delete_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='periodo_lectivo',
            field=models.CharField(default=2022, max_length=10),
            preserve_default=False,
        ),
    ]
