# Generated by Django 4.2.5 on 2023-09-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0004_remove_estudiante_id_alter_estudiante_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=10)),
                ('codigo', models.IntegerField()),
                ('email_institucional', models.EmailField(max_length=254)),
                ('email_personal', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('periodo_lectivo', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
