# Generated by Django 4.2.5 on 2023-09-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0005_estudiantes_delete_estudiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
    ]
