# Generated by Django 4.2.5 on 2023-09-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0006_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
