# Generated by Django 4.2.5 on 2023-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0007_alter_estudiante_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='periodo_lectivo',
            field=models.CharField(default='2023-1', max_length=10),
        ),
    ]
