# Generated by Django 4.2.5 on 2023-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0008_alter_estudiante_periodo_lectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='periodo_lectivo',
            field=models.CharField(default='2024-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
