# Generated by Django 4.2.5 on 2023-09-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0009_alter_estudiante_periodo_lectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='periodo_lectivo',
            field=models.CharField(default='2024-1', max_length=255),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='programa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=255),
        ),
    ]
