# Generated by Django 4.2.5 on 2023-09-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0010_alter_estudiante_codigo_alter_estudiante_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_practica', models.CharField(max_length=255)),
                ('aprobación_Programa', models.CharField(max_length=255)),
                ('matriculado_Academica_y_Financieramente', models.CharField(max_length=255)),
                ('inscripcion', models.CharField(max_length=255)),
                ('curso_induccion_y_rl', models.CharField(max_length=255)),
                ('ruta_preparacion_vida_laboral', models.CharField(max_length=255)),
                ('envio_hv', models.CharField(max_length=255)),
                ('titulo_tecnico_o_tecnologo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Contrato', models.CharField(max_length=255)),
                ('fecha_Inicio', models.CharField(max_length=255)),
                ('fecha_Final', models.CharField(max_length=255)),
                ('encargado_Proceso_Seleccion', models.CharField(max_length=255)),
                ('datos_Tutor_O_Jefe_Directivo', models.CharField(max_length=255)),
                ('documentos_Pendientes', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Estado_Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practica_Donde_Labora_EmpresaFliar_Emprendim_Otro', models.CharField(max_length=255, null=True)),
                ('estado_ubicación', models.CharField(max_length=255, null=True)),
                ('comentarios', models.CharField(max_length=255, null=True)),
                ('codigo_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Archivos.estudiante')),
                ('id_contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Archivos.contrato')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Archivos.aspirantes')),
            ],
        ),
        migrations.AddField(
            model_name='aspirantes',
            name='codigo_estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Archivos.estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='plan_estudios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Archivos.plan_estudios'),
        ),
    ]
