# Generated by Django 4.2.5 on 2023-09-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0011_aspirantes_contrato_plan_estudios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='plan_estudios',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Archivos.plan_estudios'),
        ),
    ]
