# Generated by Django 4.2.5 on 2023-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0012_alter_estudiante_plan_estudios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
