# Generated by Django 4.2.5 on 2023-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0014_alter_estudiante_periodo_lectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitores',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('correo_institucional', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('horas_disponibles', models.CharField(max_length=255)),
            ],
        ),
    ]
