# Generated by Django 4.2.5 on 2023-10-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0016_monitores_programa_alter_monitores_horas_disponibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(default='dsdd812', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='monitores',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Archivos.programa'),
        ),
    ]
