# Generated by Django 4.2.5 on 2023-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0017_programa_alter_monitores_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='programa',
            field=models.CharField(default='sin programa', max_length=255),
        ),
    ]
