# Generated by Django 4.1.10 on 2023-10-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0017_perfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='correo',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='codigo',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
