# Generated by Django 4.2.5 on 2023-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0018_alter_programa_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='codigo',
            field=models.CharField(default='sin codigo', max_length=255),
        ),
        migrations.AddField(
            model_name='programa',
            name='facultad',
            field=models.CharField(default='sin facultad', max_length=255),
        ),
    ]
