# Generated by Django 4.2.5 on 2023-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0020_perfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='codigo',
            field=models.CharField(default='1', max_length=255, primary_key=True, serialize=False),
        ),
    ]
