# Generated by Django 4.1.10 on 2023-10-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0021_remove_perfiles_id_alter_perfiles_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programa',
            new_name='Programas',
        ),
    ]
