# Generated by Django 4.1.10 on 2023-10-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0022_rename_programa_programas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='docente_asignado',
            field=models.OneToOneField(default='Ninguno', null=True, on_delete=django.db.models.deletion.CASCADE, to='Archivos.monitores'),
        ),
        migrations.AddField(
            model_name='monitores',
            name='estado',
            field=models.BooleanField(default=1),
        ),
    ]
