# Generated by Django 4.2.5 on 2023-10-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0022_rename_programa_programas'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
