# Generated by Django 4.1.10 on 2023-10-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0024_alter_estudiante_docente_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitores',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
