# Generated by Django 4.1.10 on 2023-10-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0026_alter_monitores_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='docente_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Archivos.monitores'),
        ),
    ]
