# Generated by Django 4.1.10 on 2023-10-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0023_uploadedfile'),
        ('Archivos', '0030_alter_estudiante_docente_asignado'),
    ]

    operations = [
    ]
