# Generated by Django 4.2.5 on 2023-10-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0031_merge_20231018_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedARLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estudianteId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Archivos.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedEPSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estudianteId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Archivos.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLABORALFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estudianteId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Archivos.estudiante')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
