# Generated by Django 4.1.10 on 2023-10-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0034_alter_uploadedarlfile_estudianteid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('fecha_inicio', models.DateTimeField(default='', max_length=255)),
                ('fecha_fin', models.DateTimeField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='codigo',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='usuario',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
