# Generated by Django 4.1.10 on 2023-11-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0035_semestres_remove_perfiles_codigo_perfiles_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Archivos.monitores')),
            ],
        ),
    ]
