# Generated by Django 4.1.10 on 2023-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0036_coordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestres',
            name='fecha_fin',
            field=models.DateField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='semestres',
            name='fecha_inicio',
            field=models.DateField(default='', max_length=255),
        ),
    ]
