# Generated by Django 4.2.7 on 2023-11-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0038_alter_estudiante_periodo_lectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='periodo_lectivo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
