# Generated by Django 4.1.10 on 2023-11-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0039_alter_estudiante_periodo_lectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='correo',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
