# Generated by Django 4.1.10 on 2023-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0040_perfiles_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado_legalizacion',
            field=models.CharField(default='Incompleto', max_length=255, null=True),
        ),
    ]
