# Generated by Django 4.2.7 on 2023-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0040_perfiles_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado_legalizacion',
            field=models.CharField(choices=[('Aprobado o legalizado', 'Aprobado o legalizado'), ('Pendiente por legalizar', 'Pendiente por legalizar'), ('Pendiente por cargar archivos', 'Pendiente por cargar archivos')], default='Pendiente por cargar archivos', max_length=50),
        ),
    ]
