# Generated by Django 4.2.7 on 2023-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0041_estudiante_estado_legalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_legalizacion',
            field=models.CharField(choices=[('Legalizado', 'Legalizado'), ('Pendiente por legalizar', 'Pendiente por legalizar'), ('Pendiente por cargar archivos', 'Pendiente por cargar archivos')], default='Pendiente por cargar archivos', max_length=50),
        ),
    ]
