# Generated by Django 4.1.10 on 2023-11-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0041_estudiante_estado_legalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='periodo_lectivo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
